### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by chrismichaels84** [chrismichaels84/data-manager#24]
There are only a few more features I would like to add before hitting 1.0.

v0.9.0 will be a feature freeze for 1.0. That is, no *new* features before 1.0, only bugfixes and refactoring.

For v0.8.6
  - [ ] `initFromJson()`
  - [ ] Basic Collections

For v0.9.0
  - [ ] Full collections (frozen for 1.0)
  - [ ] More `Manager` classes

For v1.0
  - [ ] Test coverage to 100%
  - [ ] Review documentation
  - [ ] Scrutinizer to 9+
  - [ ] Insight platinum
  - [ ] Marketing site
